# version: 0.0.2
AWSTemplateFormatVersion: 2010-09-09
Description: Datadog Cloud Cost Management Setup (CUR 2.0 / BCM Data Exports)
Parameters:
  CloudCostBucketName:
    Type: String
    Description: The name of the S3 bucket for storing the cost and usage reports.
    MinLength: 1
  CloudCostBucketRegion:
    Type: String
    Description: The AWS region where the S3 bucket is located.
    MinLength: 1
  CloudCostReportPrefix:
    Type: String
    Description: The prefix to be added to the cost and usage report files in the S3 bucket.
    MinLength: 1
  CloudCostReportName:
    Type: String
    Description: The name of the cost and usage report (the BCM Data Exports export name).
    MinLength: 1
  DatadogIntegrationRole:
    Type: String
    Description: The name of the IAM role that has been integrated with Datadog.
    MinLength: 1
  CreateCloudCostReport:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether a new Cost and Usage Report (CUR 2.0 export) is created, or an existing one is used.
  CreateCloudCostBucket:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether the S3 bucket for storing the Cost and Usage Report is created, or an existing one is used. Ignored if CreateCloudCostReport is false.

Conditions:
  ShouldCreateCloudCostReport:
    Fn::Equals:
      - Ref: CreateCloudCostReport
      - true
  ShouldCreateCloudCostBucket:
    Fn::And:
      - Fn::Equals:
          - Ref: CreateCloudCostBucket
          - true
      - !Condition ShouldCreateCloudCostReport # If CUR already exists, we don't need to create the bucket

Resources:
  DatadogCCMIAMPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: !Sub "datadog-ccm-iam-policy--${CloudCostBucketName}-${CloudCostReportPrefix}-${CloudCostReportName}"
      RoleName: !Ref DatadogIntegrationRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ReadCloudCostBucket
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Sub "arn:${AWS::Partition}:s3:::${CloudCostBucketName}"
          - Sid: GetBill
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${CloudCostBucketName}/${CloudCostReportPrefix}/${CloudCostReportName}/*"
          - Sid: CheckAccuracy
            Effect: Allow
            Action:
              - ce:Get*
            Resource: "*"
          - Sid: ListCURs
            Effect: Allow
            Action:
              - cur:DescribeReportDefinitions
              - bcm-data-exports:GetExport
              - bcm-data-exports:ListExports
            Resource: "*"
          - Sid: ListOrganizations
            Effect: Allow
            Action:
              - organizations:Describe*
              - organizations:List*
            Resource: "*"

  DDCloudCostBucket:
    Condition: ShouldCreateCloudCostBucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CloudCostBucketName

  DDCloudCostBucketAccessPolicy:
    Condition: ShouldCreateCloudCostBucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DDCloudCostBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - billingreports.amazonaws.com
                - bcm-data-exports.amazonaws.com
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
            Resource:
              - !Sub ${DDCloudCostBucket.Arn}
              - !Sub ${DDCloudCostBucket.Arn}/*
            Condition:
              StringLike:
                aws:SourceArn:
                  - !Sub arn:*:cur:*:${AWS::AccountId}:definition/*
                  - !Sub arn:*:bcm-data-exports:*:${AWS::AccountId}:export/*
                aws:SourceAccount: !Sub ${AWS::AccountId}

  BucketWaitHandle:
    Condition: ShouldCreateCloudCostBucket
    DependsOn: DDCloudCostBucketAccessPolicy
    Type: "AWS::CloudFormation::WaitConditionHandle"

  EmptyWaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  BucketWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle:
        !If [
          ShouldCreateCloudCostBucket,
          !Ref BucketWaitHandle,
          !Ref EmptyWaitHandle,
        ]
      Timeout: "1"
      Count: 0

  DDCURExport:
    Condition: ShouldCreateCloudCostReport
    DependsOn: BucketWaitCondition
    Type: AWS::BCMDataExports::Export
    Properties:
      Export:
        Name: !Ref CloudCostReportName
        DataQuery:
          QueryStatement: >-
            SELECT
            bill_bill_type, bill_billing_entity, bill_billing_period_end_date, bill_billing_period_start_date,
            bill_invoice_id, bill_invoicing_entity, bill_payer_account_id, bill_payer_account_name,
            cost_category, discount, discount_bundled_discount, discount_total_discount,
            identity_line_item_id, identity_time_interval, line_item_availability_zone, line_item_blended_cost,
            line_item_blended_rate, line_item_currency_code, line_item_legal_entity, line_item_line_item_description,
            line_item_line_item_type, line_item_net_unblended_cost, line_item_net_unblended_rate,
            line_item_normalization_factor, line_item_normalized_usage_amount, line_item_operation,
            line_item_product_code, line_item_resource_id, line_item_tax_type, line_item_unblended_cost,
            line_item_unblended_rate, line_item_usage_account_id, line_item_usage_account_name, line_item_usage_amount,
            line_item_usage_end_date, line_item_usage_start_date, line_item_usage_type, line_item_user_identifier,
            pricing_currency, pricing_lease_contract_length, pricing_offering_class, pricing_public_on_demand_cost,
            pricing_public_on_demand_rate, pricing_purchase_option, pricing_rate_code, pricing_rate_id, pricing_term,
            pricing_unit, product, product_comment, product_fee_code, product_fee_description, product_from_location,
            product_from_location_type, product_from_region_code, product_instance_family, product_instance_type,
            product_instancesku, product_location, product_location_type, product_operation, product_pricing_unit,
            product_product_family, product_region_code, product_servicecode, product_sku, product_to_location,
            product_to_location_type, product_to_region_code, product_usagetype,
            reservation_amortized_upfront_cost_for_usage, reservation_amortized_upfront_fee_for_billing_period,
            reservation_availability_zone, reservation_effective_cost, reservation_end_time,
            reservation_modification_status, reservation_net_amortized_upfront_cost_for_usage,
            reservation_net_amortized_upfront_fee_for_billing_period, reservation_net_effective_cost,
            reservation_net_recurring_fee_for_usage, reservation_net_unused_amortized_upfront_fee_for_billing_period,
            reservation_net_unused_recurring_fee, reservation_net_upfront_value,
            reservation_normalized_units_per_reservation, reservation_number_of_reservations,
            reservation_recurring_fee_for_usage, reservation_reservation_a_r_n, reservation_start_time,
            reservation_subscription_id, reservation_total_reserved_normalized_units, reservation_total_reserved_units,
            reservation_units_per_reservation, reservation_unused_amortized_upfront_fee_for_billing_period,
            reservation_unused_normalized_unit_quantity, reservation_unused_quantity, reservation_unused_recurring_fee,
            reservation_upfront_value, resource_tags, savings_plan_amortized_upfront_commitment_for_billing_period,
            savings_plan_end_time, savings_plan_instance_type_family,
            savings_plan_net_amortized_upfront_commitment_for_billing_period,
            savings_plan_net_recurring_commitment_for_billing_period, savings_plan_net_savings_plan_effective_cost,
            savings_plan_offering_type, savings_plan_payment_option, savings_plan_purchase_term,
            savings_plan_recurring_commitment_for_billing_period, savings_plan_region, savings_plan_savings_plan_a_r_n,
            savings_plan_savings_plan_effective_cost, savings_plan_savings_plan_rate, savings_plan_start_time,
            savings_plan_total_commitment_to_date, savings_plan_used_commitment, tags
            FROM COST_AND_USAGE_REPORT
          TableConfigurations:
            COST_AND_USAGE_REPORT:
              TIME_GRANULARITY: HOURLY
              INCLUDE_RESOURCES: "TRUE"
              INCLUDE_SPLIT_COST_ALLOCATION_DATA: "TRUE"
              INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY: "FALSE"
              BILLING_VIEW_ARN: !Sub "arn:${AWS::Partition}:billing::${AWS::AccountId}:billingview/primary"
        DestinationConfigurations:
          S3Destination:
            S3Bucket: !Ref CloudCostBucketName
            S3Prefix: !Ref CloudCostReportPrefix
            S3Region: !Ref CloudCostBucketRegion
            S3OutputConfigurations:
              OutputType: CUSTOM
              Format: PARQUET
              Compression: PARQUET
              Overwrite: CREATE_NEW_REPORT
        RefreshCadence:
          Frequency: SYNCHRONOUS
