# version: v<VERSION_PLACEHOLDER>
AWSTemplateFormatVersion: '2010-09-09'
Description: Extends the Datadog Agentless Scanner Delegate Role to allow copying snapshots.

Conditions:
  AccountIdProvided: !Not [!Equals [!Ref AWSAccountId, '']]
  InvalidAccountId: !And
    - !Condition AccountIdProvided
    - !Not [!Equals [!Ref AWSAccountId, !Ref 'AWS::AccountId']]

Parameters:
  ScannerDelegateRoleName:
    Type: String
    Description: The name of the role assumed by the Datadog Agentless Scanner
    Default: DatadogAgentlessScannerDelegateRole
  AccountId:
    Type: String
    Description: The AWS Account ID where this template is being deployed (optional validation)
    AllowedPattern: "^[0-9]{12}$"

Rules:
  MustMatchAccountId:
    AssertDescription: 'Checking that provided account ID matches the actual AWS account ID'
    Assertions:
      - Assert: !Equals [!Ref AWS::AccountId, !Ref AccountId]
        AssertDescription: 'The provided account ID must match the AWS account ID of your current session where the stack is being deployed.'

Resources:
  ScannerDelegateRoleCopySnapshotPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref ScannerDelegateRoleName
      PolicyName: ScannerDelegateRoleCopySnapshotPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DatadogAgentlessScannerCopySnapshotSource
            Action: 'ec2:CopySnapshot'
            Effect: Allow
            Resource: 'arn:aws:ec2:*:*:snapshot/snap-*'
          - Sid: DatadogAgentlessScannerCopySnapshotDestination
            Action: 'ec2:CopySnapshot'
            Effect: Allow
            Resource: 'arn:aws:ec2:*:*:snapshot/${*}'
            Condition:
              'ForAllValues:StringLike':
                'aws:TagKeys': DatadogAgentlessScanner*
              StringEquals:
                'aws:RequestTag/DatadogAgentlessScanner': 'true'
