AWSTemplateFormatVersion: '2010-09-09'
Description: Extends the Datadog Agentless Scanner Delegate Role to allow copying snapshots.

Conditions:
  AccountIdProvided: !Not [!Equals [!Ref AWSAccountId, '']]
  InvalidAccountId: !And
    - !Condition AccountIdProvided
    - !Not [!Equals [!Ref AWSAccountId, !Ref 'AWS::AccountId']]

Parameters:
  ScannerDelegateRoleName:
    Type: String
    Description: The name of the role assumed by the Datadog Agentless Scanner
    Default: DatadogAgentlessScannerDelegateRole
  AWSAccountId:
    Type: String
    Description: The AWS Account ID where this template is being deployed (optional validation)
    Default: ''
    AllowedPattern: '^$|[0-9]{12}'
    ConstraintDescription: Must be empty or a valid 12-digit AWS Account ID

Rules:
  ValidateAccountId:
    RuleCondition: !Condition InvalidAccountId
    Assertions:
      - Assert: !Not [!Condition InvalidAccountId]
        AssertDescription: !Sub 'Account ID mismatch: provided ${AWSAccountId} does not match deployment account ${AWS::AccountId}'

Resources:
  ScannerDelegateRoleCopySnapshotPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref ScannerDelegateRoleName
      PolicyName: ScannerDelegateRoleCopySnapshotPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DatadogAgentlessScannerCopySnapshotSource
            Action: 'ec2:CopySnapshot'
            Effect: Allow
            Resource: 'arn:aws:ec2:*:*:snapshot/snap-*'
          - Sid: DatadogAgentlessScannerCopySnapshotDestination
            Action: 'ec2:CopySnapshot'
            Effect: Allow
            Resource: 'arn:aws:ec2:*:*:snapshot/${*}'
            Condition:
              'ForAllValues:StringLike':
                'aws:TagKeys': DatadogAgentlessScanner*
              StringEquals:
                'aws:RequestTag/DatadogAgentlessScanner': 'true'
