AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Datadog AWS Integration
Parameters:
  ExternalId:
    Description: >-
      External ID for the Datadog role (generate at
      https://app.datadoghq.com/account/settings#integrations/amazon-web-services)
    Type: String
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  ResourceCollectionPermissions:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: >-
      Set this value to "true" to add permissions for Datadog to collect resource configuration data.
  DdAWSAccountId:
    Description: >-
      Datadog AWS account ID allowed to assume the integration IAM role. DO NOT CHANGE!
    Type: String
    Default: "464622532012"
Conditions:
  ShouldInstallSecurityAuditPolicy:
    Fn::Equals:
      - Ref: ResourceCollectionPermissions
      - true
Resources:
  DatadogIntegrationRole:
    Type: "AWS::IAM::Role"
    Metadata:
      cfn-lint:
        config:
          # cfn-lint does not yet support "Fn::Transform"
          # This policy needs broad read permissions to allow Datadog to collect metrics and metadata
          ignore_checks:
            - E3002
            - E3003
            - EIAMPolicyActionWildcard
            - EIAMPolicyWildcardResource
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${DdAWSAccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalId
      Path: /
      RoleName: !Ref IAMRoleName
      ManagedPolicyArns:
        !If [
          ShouldInstallSecurityAuditPolicy,
          [!Sub "arn:${AWS::Partition}:iam::aws:policy/SecurityAudit"],
          !Ref AWS::NoValue,
        ]
      Policies:
        - PolicyName: DatadogAWSIntegrationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - "apigateway:GET"
                  - "autoscaling:Describe*"
                  - "backup:List*"
                  - "backup:ListRecoveryPointsByBackupVault"
                  - "bcm-data-exports:GetExport"
                  - "bcm-data-exports:ListExports"
                  - "bedrock:GetAgent"
                  - "bedrock:GetAgentAlias"
                  - "bedrock:GetFlow"
                  - "bedrock:GetFlowAlias"
                  - "bedrock:GetGuardrail"
                  - "bedrock:GetImportedModel"
                  - "bedrock:GetInferenceProfile"
                  - "bedrock:GetMarketplaceModelEndpoint"
                  - "bedrock:ListAgentAliases"
                  - "bedrock:ListAgents"
                  - "bedrock:ListFlowAliases"
                  - "bedrock:ListFlows"
                  - "bedrock:ListGuardrails"
                  - "bedrock:ListImportedModels"
                  - "bedrock:ListInferenceProfiles"
                  - "bedrock:ListMarketplaceModelEndpoints"
                  - "bedrock:ListPromptRouters"
                  - "bedrock:ListProvisionedModelThroughputs"
                  - "budgets:ViewBudget"
                  - "cassandra:Select"
                  - "cloudfront:GetDistributionConfig"
                  - "cloudfront:ListDistributions"
                  - "cloudtrail:DescribeTrails"
                  - "cloudtrail:GetTrailStatus"
                  - "cloudtrail:LookupEvents"
                  - "cloudwatch:Describe*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "codedeploy:BatchGet*"
                  - "codedeploy:List*"
                  - "cur:DescribeReportDefinitions"
                  - "directconnect:Describe*"
                  - "dynamodb:Describe*"
                  - "dynamodb:List*"
                  - "ec2:Describe*"
                  - "ec2:GetAllowedImagesSettings"
                  - "ec2:GetEbsDefaultKmsKeyId"
                  - "ec2:GetInstanceMetadataDefaults"
                  - "ec2:GetSerialConsoleAccessStatus"
                  - "ec2:GetSnapshotBlockPublicAccessState"
                  - "ec2:GetTransitGatewayPrefixListReferences"
                  - "ec2:SearchTransitGatewayRoutes"
                  - "ecs:Describe*"
                  - "ecs:List*"
                  - "elasticache:Describe*"
                  - "elasticache:List*"
                  - "elasticfilesystem:DescribeAccessPoints"
                  - "elasticfilesystem:DescribeFileSystems"
                  - "elasticfilesystem:DescribeTags"
                  - "elasticloadbalancing:Describe*"
                  - "elasticmapreduce:Describe*"
                  - "elasticmapreduce:List*"
                  - "es:DescribeElasticsearchDomains"
                  - "es:ListDomainNames"
                  - "es:ListTags"
                  - "events:CreateEventBus"
                  - "fsx:DescribeFileSystems"
                  - "fsx:ListTagsForResource"
                  - "glacier:GetVaultNotifications"
                  - "glue:ListRegistries"
                  - "health:DescribeAffectedEntities"
                  - "health:DescribeEventDetails"
                  - "health:DescribeEvents"
                  - "kinesis:Describe*"
                  - "kinesis:List*"
                  - "lambda:GetPolicy"
                  - "lambda:List*"
                  - "lightsail:GetInstancePortStates"
                  - "logs:DeleteSubscriptionFilter"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:DescribeSubscriptionFilters"
                  - "logs:FilterLogEvents"
                  - "logs:PutSubscriptionFilter"
                  - "logs:TestMetricFilter"
                  - "oam:ListAttachedLinks"
                  - "oam:ListSinks"
                  - "organizations:Describe*"
                  - "organizations:List*"
                  - "rds:Describe*"
                  - "rds:List*"
                  - "redshift:DescribeClusters"
                  - "redshift:DescribeLoggingStatus"
                  - "route53:List*"
                  - "s3:GetBucketLocation"
                  - "s3:GetBucketLogging"
                  - "s3:GetBucketNotification"
                  - "s3:GetBucketTagging"
                  - "s3:ListAccessGrants"
                  - "s3:ListAllMyBuckets"
                  - "s3:PutBucketNotification"
                  # For S3 Directory Buckets, the s3 calls are with the s3express prefix
                  # https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3express.html
                  - "s3express:GetBucketPolicy"
                  - "s3express:GetEncryptionConfiguration"
                  - "s3express:ListAllMyDirectoryBuckets"
                  - "savingsplans:DescribeSavingsPlanRates"
                  - "savingsplans:DescribeSavingsPlans"
                  - "ses:Get*"
                  - "secretsmanager:GetResourcePolicy"
                  - "sns:GetSubscriptionAttributes"
                  - "sns:List*"
                  - "sns:Publish"
                  - "sqs:ListQueues"
                  - "states:DescribeStateMachine"
                  - "states:ListStateMachines"
                  - "support:DescribeTrustedAdvisor*"
                  - "support:RefreshTrustedAdvisorCheck"
                  - "tag:GetResources"
                  - "tag:GetTagKeys"
                  - "tag:GetTagValues"
                  - "timestream:DescribeEndpoints"
                  - "timestream:ListTables"
                  - "waf-regional:GetRule"
                  - "waf-regional:GetRuleGroup"
                  - "waf-regional:ListRuleGroups"
                  - "waf-regional:ListRules"
                  - "waf:GetRuleGroup"
                  - "waf:GetRule"
                  - "waf:ListRuleGroups"
                  - "waf:ListRules"
                  - "wafv2:GetIPSet"
                  - "wafv2:GetLoggingConfiguration"
                  - "wafv2:GetRegexPatternSet"
                  - "wafv2:GetRuleGroup"
                  - "wafv2:ListLoggingConfigurations"
                  - "xray:BatchGetTraces"
                  - "xray:GetTraceSummaries"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required
        Parameters:
          - ExternalId
          - IAMRoleName
      - Label:
          default: Optional
        Parameters:
          - CloudSecurityPostureManagementPermissions
          - DdAWSAccountId
