AWSTemplateFormatVersion: 2010-09-09
Description: Configures the Datadog AWS Integration
Parameters:
  DatadogApiKey:
    Description: >-
      API key for the Datadog account
    Type: String
    NoEcho: true
    Default: ""
  DatadogAppKey:
    Description: >-
      APP key for the Datadog account
    Type: String
    NoEcho: true
    Default: ""
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ap2.datadoghq.com
      - ddog-gov.com
  IAMRoleName:
    Description: >-
      The name of the IAM role created for Datadog's use.
    Type: String
  DisableMetricCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling metric collection for this account will lead to a loss in visibility into your AWS services.
      Disable this if you only want to collect tags or resource configuration information from this AWS account,
      and do not want to use Datadog Infrastructure Monitoring.
    Default: false
  DisableResourceCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling resource collection for this account will lead to a loss in visibility into your AWS services.
      Disable this if you do not want to collect configuration information for the resources in this AWS account.
    Default: false
  CloudSecurityPostureManagement:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Add the AWS Managed SecurityAudit policy to your Datadog AWS Integration role, and enable
      Datadog Cloud Security Posture Management (CSPM) to start performing configuration checks across your AWS account.
      Datadog CSPM is a product that automatically detects resource misconfigurations in your AWS account according to
      industry benchmarks. More info: https://www.datadoghq.com/product/security-platform/cloud-security-posture-management/
    Default: false
Resources:
  DatadogAPIHandlerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  DatadogAWSAccountIntegration:
    Type: "Custom::DatadogAWSAccountIntegration"
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !GetAtt DatadogAPICallFunction.Arn
      APIKey: !Ref DatadogApiKey
      APPKey: !Ref DatadogAppKey
      ApiURL: !Ref DatadogSite
      AccountId: !Ref AWS::AccountId
      RoleName: !Ref IAMRoleName
      AWSPartition: !Ref AWS::Partition
      AccountTags: [!Sub "aws_account:${AWS::AccountId}"]
      CloudSecurityPostureManagement: !Ref CloudSecurityPostureManagement
      DisableMetricCollection: !Ref DisableMetricCollection
      DisableResourceCollection: !Ref DisableResourceCollection
  DatadogAPICallFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "A function to call the Datadog API."
      Role: !GetAtt DatadogAPIHandlerLambdaExecutionRole.Arn
      Handler: "index.handler"
      LoggingConfig:
        ApplicationLogLevel: "INFO"
        LogFormat: "JSON"
      Runtime: "python3.11"
      Timeout: 5
      Code:
        ZipFile: |
          <ZIPFILE_PLACEHOLDER>
Outputs:
  ExternalId:
    Description: Datadog AWS Integration ExternalId
    Value: !GetAtt DatadogAWSAccountIntegration.ExternalId
