AWSTemplateFormatVersion: "2010-09-09"
Description: Calls the Datadog Agentless Scanning API to enable or disable agentless scanning features.

Parameters:
  DatadogAPIKey:
    Type: String
    AllowedPattern: "[0-9a-f]{32}"
    Description: API key for the Datadog account
    NoEcho: true

  DatadogAPPKey:
    Type: String
    AllowedPattern: "[0-9a-f]{40}"
    Description: Application key for the Datadog account
    NoEcho: true

  DatadogSite:
    Type: String
    Description: The Datadog site to use for the Datadog Agentless Scanner
    Default: datadoghq.com
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ap2.datadoghq.com

  AgentlessHostScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enable Agentless Scanning of host vulnerabilities.
    Default: false

  AgentlessContainerScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enable Agentless Scanning of container vulnerabilities.
    Default: false

  AgentlessLambdaScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enable Agentless Scanning of Lambda vulnerabilities.
    Default: false

  AgentlessSensitiveDataScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enable Agentless Scanning of datastores (S3 buckets).
    Default: false

Resources:
  LambdaExecutionRoleDatadogAgentlessAPICall:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  DatadogAgentlessAPICall:
    Type: "Custom::DatadogAgentlessAPICall"
    Properties:
      ServiceToken: !GetAtt "DatadogAgentlessAPICallFunction.Arn"
      APIKey: !Ref "DatadogAPIKey"
      APPKey: !Ref "DatadogAPPKey"
      DatadogSite: !Ref "DatadogSite"
      AccountId: !Ref "AWS::AccountId"
      Hosts: !Ref "AgentlessHostScanning"
      Containers: !Ref "AgentlessContainerScanning"
      Lambdas: !Ref "AgentlessLambdaScanning"
      SensitiveData: !Ref "AgentlessSensitiveDataScanning"

  DatadogAgentlessAPICallFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: A function to call the Datadog Agentless API.
      Role: !GetAtt LambdaExecutionRoleDatadogAgentlessAPICall.Arn
      Handler: "index.handler"
      LoggingConfig:
        ApplicationLogLevel: "INFO"
        LogFormat: "JSON"
      Runtime: "python3.11"
      Timeout: 30
      Code:
        ZipFile: |
          <ZIPFILE_PLACEHOLDER>
