AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration API Call
Parameters:
  DatadogApiKey:
    Description: >-
      API key for the Datadog account
    Type: String
    NoEcho: true
    Default: ""
  DatadogAppKey:
    Description: >-
      APP key for the Datadog account
    Type: String
    NoEcho: true
    Default: ""
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ddog-gov.com
  RoleName:
    Description: >-
      The name of the IAM role created for Datadog's use.
    Type: String
  DisableMetricCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling metric collection for this account will lead to a loss in visibility into your AWS services.
      Disable this if you only want to collect tags or resource configuration information from this AWS account,
      and do not want to use Datadog Infrastructure Monitoring.
    Default: false
  CloudSecurityPostureManagement:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Add the AWS Managed SecurityAudit policy to your Datadog AWS Integration role, and enable
      Datadog Cloud Security Posture Management (CSPM) to start performing configuration checks across your AWS account.
      Datadog CSPM is a product that automatically detects resource misconfigurations in your AWS account according to
      industry benchmarks. More info: https://www.datadoghq.com/product/security-platform/cloud-security-posture-management/
    Default: false
Resources:
  LambdaExecutionRoleDatadogAPIHandler:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  # Retrieving secrets passed in via SecretsManager Arn
  DatadogAPIHandler:
    Type: "Custom::DatadogAPIHandler"
    Properties:
      ServiceToken: !GetAtt DatadogAPIHandlerFunction.Arn
      APIKey: !Ref DatadogApiKey
      APPKey: !Ref DatadogAppKey
      ApiURL: !Ref DatadogSite
      AccountId: !Ref AWS::AccountId
      RoleName: !Ref RoleName
      AWSPartition: !Ref AWS::Partition
      AccountTags: [!Sub "aws_account:${AWS::AccountId}"]
      CloudSecurityPostureManagement: !Ref CloudSecurityPostureManagement
      DisableMetricCollection: !Ref DisableMetricCollection
  DatadogAPIHandlerFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "A function to call the Datadog API."
      Role: !GetAtt LambdaExecutionRoleDatadogAPIHandler.Arn
      Handler: "index.handler"
      Runtime: "python3.11"
      Timeout: 5
      Code:
        ZipFile: |
          import json
          import logging
          import signal
          from urllib.request import Request
          import urllib.parse
          import cfnresponse

          LOGGER = logging.getLogger()
          LOGGER.setLevel(logging.INFO)

          API_CALL_SOURCE_HEADER_VALUE = "cfn-quick-start"


          def call_datadog_api(event, method):
              api_key = event["ResourceProperties"]["APIKey"]
              app_key = event["ResourceProperties"]["APPKey"]
              api_url = event["ResourceProperties"]["ApiURL"]
              account_id = event["ResourceProperties"]["AccountId"]
              role_name = event["ResourceProperties"]["RoleName"]
              aws_partition = event["ResourceProperties"]["AWSPartition"]
              account_tags = event["ResourceProperties"]["AccountTags"]
              cspm = event["ResourceProperties"]["CloudSecurityPostureManagement"]
              metrics_disabled = event["ResourceProperties"]["DisableMetricCollection"]

              # Make the url Request
              url = "https://api." + api_url + "/api/v2/integration/aws/accounts"
              headers = {
                  "DD-API-KEY": api_key,
                  "DD-APPLICATION-KEY": app_key,
                  "Dd-Aws-Api-Call-Source": API_CALL_SOURCE_HEADER_VALUE,
              }

              if method == "PATCH" or method == "DELETE":
                  url = url + "/" + account_id

              if method == "DELETE":
                  # DELETE request has no body
                  request = Request(url, headers=headers)
              else:
                  # Create the request body for POST and PATCH
                  values = {
                      "data": {
                          "id": account_id,
                          "type": "account",
                          "attributes": {
                              "aws_account": {
                                  "aws_account_id": account_id,
                                  "account_tags": account_tags,
                                  "aws_partition": aws_partition,
                                  "auth_config": {"role_name": role_name},
                                  "metrics_config": {
                                      "enabled": (metrics_disabled == "false"),
                                      "namespace_filters": {"include_all": True},
                                  },
                                  "resources_config": {
                                      "cloud_security_posture_management_collection": (
                                          cspm == "true"
                                      )
                                  },
                              }
                          },
                      }
                  }

                  data = json.dumps(values)
                  data = data.encode("utf-8")  # data should be bytes
                  request = Request(url, data=data, headers=headers)
                  request.add_header("Content-Type", "application/json; charset=utf-8")
                  request.add_header("Content-Length", len(data))

              # Send the request
              request.get_method = lambda: method
              try:
                  response = urllib.request.urlopen(request)
              except urllib.error.HTTPError as e:
                  # Return error response from API
                  response = e
              return response


          def handler(event, context):
              """Handle Lambda event from AWS"""
              try:
                  if event["RequestType"] == "Create":
                      LOGGER.info("Received Create request.")
                      response = call_datadog_api(event, "POST")
                      json_response = json.loads(response.read().decode("utf-8"))
                      if response.getcode() == 200:
                          external_id = json_response["data"]["attributes"]["aws_account"]["auth_config"]["external_id"]
                          msg = {
                              "Message": "Datadog AWS Integration created successfully.",
                              "ExternalId": external_id,
                          }
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="SUCCESS",
                              responseData=msg,
                          )
                      else:
                          LOGGER.info("Failed - exception thrown during processing.")
                          msg = {"Message": "Datadog API returned error: {}".format(json_response)}
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="FAILED",
                              responseData=msg,
                              reason=msg,
                          )

                  elif event["RequestType"] == "Update":
                      LOGGER.info("Received Update request.")
                      response = call_datadog_api(event, "PATCH")
                      json_response = json.loads(response.read().decode("utf-8"))
                      if response.getcode() == 200:
                          external_id = json_response["data"]["attributes"]["aws_account"]["auth_config"]["external_id"]
                          msg = {
                              "Message": "Datadog AWS Integration created successfully.",
                              "ExternalId": external_id,
                          }
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="SUCCESS",
                              responseData=msg,
                          )
                      else:
                          LOGGER.info("Failed - exception thrown during processing.")
                          msg = {"Message": "Datadog API returned error: {}".format(json_response)}
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="FAILED",
                              responseData=msg,
                              reason=msg,
                          )
                  elif event["RequestType"] == "Delete":
                      LOGGER.info("Received Delete request.")
                      response = call_datadog_api(event, "DELETE")
                      if response.getcode() == 204:
                          msg = {"Message": "Datadog AWS Integration deleted successfully."}
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="SUCCESS",
                              responseData=msg,
                          )
                      else:
                          json_response = json.loads(response.read().decode("utf-8"))
                          LOGGER.info("Failed - exception thrown during processing.")
                          msg = {"Message": "Datadog API returned error: {}".format(json_response)}
                          cfnresponse.send(
                              event,
                              context,
                              responseStatus="FAILED",
                              responseData=msg,
                              reason=msg,
                          )
                  else:
                      LOGGER.info("Failed - received unexpected request.")
                      msg = "Received unexpected request type: {}".format(event["RequestType"])
                      cfnresponse.send(
                          event,
                          context,
                          responseStatus="FAILED",
                          responseData={"Message": msg},
                          reason=msg,
                      )
              except Exception as e:
                  LOGGER.info("Failed - exception thrown during processing.")
                  msg = "Exception during processing: {}".format(e)
                  cfnresponse.send(
                      event,
                      context,
                      "FAILED",
                      responseData={"Message": msg},
                      reason=msg,
                  )


          def timeout_handler(_signal, _frame):
              """Handle SIGALRM"""
              raise Exception("Time exceeded")


          signal.signal(signal.SIGALRM, timeout_handler)

Outputs:
  ExternalId:
    Description: Datadog AWS Integration ExternalId
    Value: !GetAtt DatadogAPIHandler.ExternalId
