# version: <VERSION_PLACEHOLDER>
AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration
Parameters:
  APIKey:
    Description: >-
      API key for the Datadog account (find at https://app.datadoghq.com/organization-settings/api-keys).
      To enable Agentless Scanning (find at https://docs.datadoghq.com/security/cloud_security_management/agentless_scanning),
      you must use a Remote Configuration-enabled API key (find at https://docs.datadoghq.com/security/cloud_security_management/setup/agentless_scanning/)
    Type: String
    AllowedPattern: "([0-9a-f]{32})?"
    NoEcho: true
    Default: ""
  APPKey:
    Description: >-
      APP key for the Datadog account (find at https://app.datadoghq.com/organization-settings/application-keys). 
      If this template was launched from the Datadog app, this key is tied to the user that launched the template,
      and is a key specifically generated for this integration.
    Type: String
    AllowedPattern: "([0-9a-f]{40})?"
    NoEcho: true
    Default: ""
  AWSAccountType:
    Description: >-
      Select the type of AWS account you are integrating with Datadog. 
      If you are integrating with a GovCloud account, select "GovCloud", otherwise select "Standard".
    Type: String
    Default: Standard
    AllowedValues:
      - Standard
      - GovCloud
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ddog-gov.com
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  InstallLambdaLogForwarder:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Determines whether the default configuration for the Datadog Lambda Log Forwarder is installed 
      as part of this stack. This is useful for sending logs to Datadog for use in Log Management or Cloud SIEM. 
      Customers who want to customize this setup to include specific custom tags, data scrubbing or redaction rules,
      or send logs using AWS PrivateLink should select “no” and install this independently
      (https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#installation).
    Default: true
  DisableMetricCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling metric collection for this account will lead to a loss in visibility into your AWS services. 
      Disable this if you only want to collect tags or resource configuration information from this AWS account, 
      and do not want to use Datadog Infrastructure Monitoring.
    Default: false
  DisableResourceCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling resource collection for this account will lead to a loss in visibility into your AWS services. 
      Disable this if you do not want to collect configuration information for the resources in this AWS account.
    Default: false
  CloudSecurityPostureManagement:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Add the AWS Managed SecurityAudit policy to your Datadog AWS Integration role, and enable 
      Datadog Cloud Security Posture Management (CSPM) to start performing configuration checks across your AWS account.
      Datadog CSPM is a product that automatically detects resource misconfigurations in your AWS account according to 
      industry benchmarks. More info: https://www.datadoghq.com/product/security-platform/cloud-security-posture-management/
    Default: false
  AgentlessHostScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Enable Agentless Scanning of host vulnerabilities.
    Default: false
  AgentlessContainerScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Enable Agentless Scanning of container vulnerabilities.
    Default: false
  AgentlessLambdaScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Enable Agentless Scanning of Lambda vulnerabilities.
    Default: false
  AgentlessSensitiveDataScanning:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Enable Agentless Scanning of datastores (S3 buckets).
    Default: false
Rules:
  CSPMResourceCollectionValidState:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::And:
                - Fn::Equals:
                    - Ref: DisableResourceCollection
                    - 'true'
                - Fn::Equals:
                    - Ref: CloudSecurityPostureManagement
                    - 'true'
        AssertDescription: CloudSecurityPostureManagement requires ResourceCollection, must enable ResourceCollection
  AgentlessResourceCollectionValidState:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::And:
                - Fn::Equals:
                    - Ref: DisableResourceCollection
                    - 'true'
                - Fn::Or:
                    - Fn::Equals:
                        - Ref: AgentlessHostScanning
                        - 'true'
                    - Fn::Equals:
                        - Ref: AgentlessContainerScanning
                        - 'true'
                    - Fn::Equals:
                        - Ref: AgentlessLambdaScanning
                        - 'true'
                    - Fn::Equals:
                        - Ref: AgentlessSensitiveDataScanning
                        - 'true'
        AssertDescription: Agentless Scanning options require ResourceCollection, must enable ResourceCollection
Conditions:
  InstallForwarder:
    Fn::Equals:
      - !Ref InstallLambdaLogForwarder
      - true
  ResourceCollectionPermissions:
    Fn::Equals:
      - !Ref DisableResourceCollection
      - false
  EnableAgentlessScanning:
    Fn::And:
      - Fn::Not:
        - Fn::Equals:
          - !Ref DatadogSite
          - ddog-gov.com
      - Fn::Or:
        - Fn::Equals:
          - !Ref AgentlessHostScanning
          - true
        - Fn::Equals:
          - !Ref AgentlessContainerScanning
          - true
        - Fn::Equals:
          - !Ref AgentlessLambdaScanning
          - true
        - Fn::Equals:
          - !Ref AgentlessSensitiveDataScanning
          - true
  IsAP1:
    Fn::Equals:
      - !Ref DatadogSite
      - ap1.datadoghq.com
  IsGov:
    Fn::Equals:
      - !Ref DatadogSite
      - ddog-gov.com
  IsAWSGovCloud:
    Fn::Equals:
      - !Ref AWSAccountType
      - GovCloud
Resources:
  # A Macro used to generate policies for the integration IAM role based on user inputs
  DatadogAgentlessScanning:
    Type: AWS::CloudFormation::Stack
    Condition: EnableAgentlessScanning
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/<VERSION_PLACEHOLDER>/datadog_agentless_scanning.yaml"
      Parameters:
        DatadogAPIKey: !Ref APIKey
        DatadogAPPKey: !Ref APPKey
        DatadogSite: !Ref DatadogSite
        AgentlessHostScanning: !Ref AgentlessHostScanning
        AgentlessContainerScanning: !Ref AgentlessContainerScanning
        AgentlessLambdaScanning: !Ref AgentlessLambdaScanning
        AgentlessSensitiveDataScanning: !Ref AgentlessSensitiveDataScanning
        DatadogIntegrationRoleName: !Ref IAMRoleName
  DatadogAPICall:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/<VERSION_PLACEHOLDER>/datadog_integration_api_call_v2.yaml"
      Parameters:
        DatadogApiKey: !Ref APIKey
        DatadogAppKey: !Ref APPKey
        DatadogSite: !Ref DatadogSite
        IAMRoleName: !Ref IAMRoleName
        CloudSecurityPostureManagement: !Ref CloudSecurityPostureManagement
        DisableMetricCollection: !Ref DisableMetricCollection
        DisableResourceCollection: !Ref DisableResourceCollection
  # The IAM role for Datadog integration
  DatadogIntegrationRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/<VERSION_PLACEHOLDER>/datadog_integration_role.yaml"
      Parameters:
        ExternalId: !GetAtt DatadogAPICall.Outputs.ExternalId
        IAMRoleName: !Ref IAMRoleName
        ResourceCollectionPermissions: !If [ResourceCollectionPermissions, true, false]
        DdAWSAccountId: !If
          - IsAP1
          - "417141415827"
          - !If
            - IsGov
            - !If
              - IsAWSGovCloud
              - "065115117704"
              - "392588925713"
            - "464622532012"
  # The Lambda function to ship logs from S3 and CloudWatch, custom metrics and traces from Lambda functions to Datadog
  # https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring
  ForwarderStack:
    Type: AWS::CloudFormation::Stack
    Condition: InstallForwarder
    Properties:
      TemplateURL: "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml"
      Parameters:
        DdApiKey: !Ref APIKey
        DdSite: !Ref DatadogSite
Outputs:
  IAMRoleName:
    Description: AWS IAM Role named to be used with the DataDog AWS Integration 
    Value: !Ref IAMRoleName
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Condition: InstallForwarder
    Value:
      Fn::GetAtt:
        - ForwarderStack
        - Outputs.DatadogForwarderArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - APIKey
        - APPKey
        - DatadogSite
        - InstallLambdaLogForwarder
        - CloudSecurityPostureManagement
        - AgentlessHostScanning
        - AgentlessContainerScanning
        - AgentlessLambdaScanning
        - AgentlessSensitiveDataScanning
    - Label:
        default: Advanced
      Parameters:
        - IAMRoleName
        - DisableMetricCollection
    ParameterLabels:
      APIKey:
        default: "DatadogApiKey *"
      APPKey:
        default: "DatadogAppKey *"
      DatadogSite:
        default: "DatadogSite *"
      CloudSecurityPostureManagement:
        default: "CloudSecurityPostureManagement *"
      AgentlessHostScanning:
        default: "AgentlessHostScanning *"
      AgentlessContainerScanning:
        default: "AgentlessContainerScanning *"
      AgentlessLambdaScanning:
        default: "AgentlessLambdaScanning *"
      AgentlessSensitiveDataScanning:
        default: "AgentlessSensitiveDataScanning *"
      InstallLambdaLogForwarder:
        default: "InstallLambdaLogForwarder *"
