# version: <VERSION_PLACEHOLDER>
#
# WARNING: This template is designed to be launched exclusively from the Datadog UI.
#
# This template requires UI-generated parameters (WorkflowId, ExternalId) and reports
# workflow status back to Datadog. The AWS account integration is created by the Datadog
# UI after the CloudFormation stack completes successfully.
#
# For manual CloudFormation launches, please use main_v2.yaml instead, which creates
# the AWS integration directly without requiring UI coordination.
#
AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration (Workflow) - Designed for Datadog UI launches only
Parameters:
  APIKey:
    Description: >-
      API key for the Datadog account (find at https://app.datadoghq.com/organization-settings/api-keys)
    Type: String
    NoEcho: true
    Default: ""
  APPKey:
    Description: >-
      APP key for the Datadog account (find at https://app.datadoghq.com/organization-settings/application-keys).
      If this template was launched from the Datadog app, this key is tied to the user that launched the template,
      and is a key specifically generated for this integration.
    Type: String
    NoEcho: true
    Default: ""
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ap2.datadoghq.com
      - prtest07.datadoghq.com
      - ddog-gov.com
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  InstallLambdaLogForwarder:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Determines whether the default configuration for the Datadog Lambda Log Forwarder is installed
      as part of this stack. This is useful for sending logs to Datadog for use in Log Management or Cloud SIEM.
      Customers who want to customize this setup to include specific custom tags, data scrubbing or redaction rules,
      or send logs using AWS PrivateLink should select "no" and install this independently
      (https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#installation).
    Default: true
  DisableResourceCollection:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Disabling resource collection for this account will lead to a loss in visibility into your AWS services.
      Disable this if you do not want to collect configuration information for the resources in this AWS account.
    Default: false
  WorkflowId:
    Description: >-
      Unique identifier for this workflow instance. This is generated by the Datadog UI and used to track
      the progress of the CloudFormation stack deployment.
    Type: String
  ExternalId:
    Description: >-
      External ID for the IAM role trust policy. This is generated by the Datadog UI and ensures
      that only your Datadog organization can assume this role.
    Type: String
Conditions:
  InstallForwarder:
    Fn::Equals:
      - !Ref InstallLambdaLogForwarder
      - true
  NoForwarder:
    Fn::Not:
      - Condition: InstallForwarder
  ResourceCollectionPermissions:
    Fn::Equals:
      - !Ref DisableResourceCollection
      - false
  IsAP1:
    Fn::Equals:
      - !Ref DatadogSite
      - ap1.datadoghq.com
  IsAP2:
    Fn::Equals:
      - !Ref DatadogSite
      - ap2.datadoghq.com
  IsPRTEST07:
    Fn::Equals:
      - !Ref DatadogSite
      - prtest07.datadoghq.com
  IsGov:
    Fn::Equals:
      - !Ref DatadogSite
      - ddog-gov.com
  IsAWSGovCloud:
    Fn::Equals:
      - !Ref AWS::Partition
      - aws-us-gov
Resources:
  # Workflow Status Lambda - defined once, used multiple times
  WorkflowStatusLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  WorkflowStatusFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "Reports workflow status to Datadog"
      Role: !GetAtt WorkflowStatusLambdaExecutionRole.Arn
      Handler: "index.handler"
      LoggingConfig:
        ApplicationLogLevel: "INFO"
        LogFormat: "JSON"
      Runtime: "python3.11"
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import logging
          from urllib.request import Request, urlopen
          from urllib.error import HTTPError
          import cfnresponse

          LOGGER = logging.getLogger()
          LOGGER.setLevel(logging.INFO)

          def send_workflow_status(workflow_id, step, status, message, api_key, app_key, api_url, metadata=None):
              """Send workflow status to Datadog API"""
              url = f"https://api.{api_url}/api/unstable/integration/aws/workflow/setup"
              headers = {
                  "DD-API-KEY": api_key,
                  "DD-APPLICATION-KEY": app_key,
                  "Content-Type": "application/json",
                  "Accept": "application/json",
              }

              # Build attributes - include metadata if present
              attributes = {
                  "status": status.lower(),
                  "step": step,
                  "message": message
              }
              if metadata:
                  filtered_metadata = {k: v for k, v in metadata.items() if v and v != ""}
                  if filtered_metadata:
                      attributes["metadata"] = filtered_metadata

              body = {
                  "data": {
                      "id": workflow_id,
                      "type": "integration_setup_status",
                      "attributes": attributes
                  }
              }

              data = json.dumps(body).encode("utf-8")
              request = Request(url, data=data, headers=headers, method="POST")

              LOGGER.info(f"Sending workflow status: workflow_id={workflow_id}, step={step}, status={status}")

              try:
                  response = urlopen(request, timeout=25)
                  response_data = response.read().decode('utf-8')
                  LOGGER.info(f"Workflow status reported successfully: {response.getcode()}")
                  return True
              except HTTPError as e:
                  error_body = e.read().decode('utf-8') if e.fp else "No error body"
                  LOGGER.error(f"HTTP error reporting workflow status: {e.code} - {error_body}")
                  return False
              except Exception as e:
                  LOGGER.error(f"Exception reporting workflow status: {str(e)}")
                  return False

          def handler(event, context):
              """Handle Lambda event from CloudFormation"""
              LOGGER.info(f"Received event: {event['RequestType']}")

              # Handle Delete - stack is being deleted (rollback or manual deletion)
              if event["RequestType"] == "Delete":
                  try:
                      workflow_id = event["ResourceProperties"]["WorkflowId"]
                      api_key = event["ResourceProperties"]["ApiKey"]
                      app_key = event["ResourceProperties"]["AppKey"]
                      api_url = event["ResourceProperties"]["ApiURL"]

                      # Report failed status - integration setup did not complete
                      send_workflow_status(
                          workflow_id=workflow_id,
                          step="stack_deleted",
                          status="failed",
                          message="CloudFormation stack was deleted - integration setup did not complete",
                          api_key=api_key,
                          app_key=app_key,
                          api_url=api_url,
                          metadata={"stack_id": event['StackId']}
                      )
                  except Exception as e:
                      LOGGER.error(f"Error reporting stack deletion: {str(e)}")

                  # Always succeed deletion so CloudFormation can clean up
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  return

              # Ignore Update events
              if event["RequestType"] != "Create":
                  LOGGER.info(f"Skipping {event['RequestType']} - only reporting on Create and Delete")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  return

              # Handle Create - report workflow progress
              try:
                  workflow_id = event["ResourceProperties"]["WorkflowId"]
                  step = event["ResourceProperties"]["StepId"]
                  status = event["ResourceProperties"]["Status"]
                  message = event["ResourceProperties"]["Message"]
                  api_key = event["ResourceProperties"]["ApiKey"]
                  app_key = event["ResourceProperties"]["AppKey"]
                  api_url = event["ResourceProperties"]["ApiURL"]
                  metadata = event["ResourceProperties"].get("Metadata", {})

                  success = send_workflow_status(
                      workflow_id=workflow_id,
                      step=step,
                      status=status,
                      message=message,
                      api_key=api_key,
                      app_key=app_key,
                      api_url=api_url,
                      metadata=metadata
                  )

                  # Always report SUCCESS to CloudFormation (don't block stack for API issues)
                  cfnresponse.send(
                      event,
                      context,
                      cfnresponse.SUCCESS,
                      {"Message": "Workflow status reported" if success else "Failed to report status but continuing"}
                  )

              except Exception as e:
                  LOGGER.error(f"Exception in Create handler: {str(e)}")
                  # Don't fail the stack for workflow status issues
                  cfnresponse.send(
                      event,
                      context,
                      cfnresponse.SUCCESS,
                      {"Message": f"Exception occurred but continuing: {str(e)}"}
                  )

  # Step 1: Notify stack started
  NotifyStackStarted:
    Type: Custom::WorkflowStatus
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "stack_started"
      Status: "finished"
      Message: "CloudFormation stack deployment started"
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

  # Step 2: Notify starting IAM role creation
  NotifyIAMRoleCreationStarted:
    Type: Custom::WorkflowStatus
    DependsOn: NotifyStackStarted
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "iam_role_creation"
      Status: "in_progress"
      Message: "Creating IAM role..."
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

  # The IAM role for Datadog integration
  DatadogIntegrationRoleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NotifyIAMRoleCreationStarted
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/<VERSION_PLACEHOLDER>/datadog_integration_role.yaml"
      Parameters:
        ExternalId: !Ref ExternalId
        IAMRoleName: !Ref IAMRoleName
        ResourceCollectionPermissions: !If [ResourceCollectionPermissions, true, false]
        DdAWSAccountId: !If
          - IsAP1
          - "417141415827"
          - !If
            - IsAP2
            - "412381753143"
            - !If
              - IsPRTEST07
              - "393946873269"
              - !If
                - IsGov
                - !If
                  - IsAWSGovCloud
                  - "065115117704"
                  - "392588925713"
                - "464622532012"

  # Step 3: Notify IAM role creation finished
  NotifyIAMRoleCreationFinished:
    Type: Custom::WorkflowStatus
    DependsOn: DatadogIntegrationRoleStack
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "iam_role_creation"
      Status: "finished"
      Message: "IAM role created successfully"
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

  # Step 4: Notify starting log forwarder creation (if installing)
  NotifyLogForwarderCreationStarted:
    Type: Custom::WorkflowStatus
    Condition: InstallForwarder
    DependsOn: NotifyIAMRoleCreationFinished
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "log_forwarder_creation"
      Status: "in_progress"
      Message: "Creating Lambda log forwarder..."
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

  # The Lambda function to ship logs from S3 and CloudWatch, custom metrics and traces from Lambda functions to Datadog
  # https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring
  ForwarderStack:
    Type: AWS::CloudFormation::Stack
    Condition: InstallForwarder
    DependsOn: NotifyLogForwarderCreationStarted
    Properties:
      TemplateURL: "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml"
      Parameters:
        DdApiKey: !Ref APIKey
        DdSite: !Ref DatadogSite

  # Step 5: Notify log forwarder creation finished (if installed)
  NotifyLogForwarderCreationFinished:
    Type: Custom::WorkflowStatus
    Condition: InstallForwarder
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "log_forwarder_creation"
      Status: "finished"
      Message: "Lambda log forwarder created successfully"
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId
        forwarder_arn: !GetAtt ForwarderStack.Outputs.DatadogForwarderArn

  # Step 6: Final notification - stack complete (with forwarder)
  NotifyStackCompleteWithForwarder:
    Type: Custom::WorkflowStatus
    Condition: InstallForwarder
    DependsOn:
      - DatadogIntegrationRoleStack
      - NotifyIAMRoleCreationStarted
      - NotifyIAMRoleCreationFinished
      - NotifyLogForwarderCreationStarted
      - ForwarderStack
      - NotifyLogForwarderCreationFinished
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "stack_complete"
      Status: "finished"
      Message: "CloudFormation stack deployment completed successfully"
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

  # Step 6: Final notification - stack complete (without forwarder)
  NotifyStackCompleteWithoutForwarder:
    Type: Custom::WorkflowStatus
    Condition: NoForwarder
    DependsOn:
      - DatadogIntegrationRoleStack
      - NotifyIAMRoleCreationStarted
      - NotifyIAMRoleCreationFinished
    Properties:
      ServiceToken: !GetAtt WorkflowStatusFunction.Arn
      WorkflowId: !Ref WorkflowId
      StepId: "stack_complete"
      Status: "finished"
      Message: "CloudFormation stack deployment completed successfully"
      ApiKey: !Ref APIKey
      AppKey: !Ref APPKey
      ApiURL: !Ref DatadogSite
      Metadata:
        account_id: !Ref AWS::AccountId
        stack_id: !Ref AWS::StackId

Outputs:
  IAMRoleName:
    Description: AWS IAM Role named to be used with the DataDog AWS Integration
    Value: !Ref IAMRoleName
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Condition: InstallForwarder
    Value:
      Fn::GetAtt:
        - ForwarderStack
        - Outputs.DatadogForwarderArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - APIKey
        - APPKey
        - DatadogSite
        - WorkflowId
        - ExternalId
        - InstallLambdaLogForwarder
    - Label:
        default: Advanced
      Parameters:
        - IAMRoleName
        - DisableResourceCollection
    ParameterLabels:
      APIKey:
        default: "DatadogApiKey *"
      APPKey:
        default: "DatadogAppKey *"
      DatadogSite:
        default: "DatadogSite *"
      WorkflowId:
        default: "WorkflowId *"
      ExternalId:
        default: "ExternalId *"
      InstallLambdaLogForwarder:
        default: "InstallLambdaLogForwarder *"
