AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration
Parameters:
  APIKey:
    Description: >-
      API key for the Datadog account (find at https://app.datadoghq.com/organization-settings/api-keys)
    Type: String
    Default: ""
  APPKey:
    Description: >-
      APP key for the Datadog account (find at https://app.datadoghq.com/organization-settings/application-keys). 
      If this template was launched from the Datadog app, this key is tied to the user that launched the template,
      and is a key specifically generated for this integration.
    Type: String
    Default: ""
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ddog-gov.com
  Products:
    Type: String
    Description: >-
      A comma separated list of relevant Datadog products you want to use with this account.
      Chose from: Infrastructure Monitoring, Serverless Monitoring, Log Management, Cloud Security Posture Management
    Default: "Infrastructure Monitoring,Serverless Monitoring,Log Management"
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  InstallLambdaLogForwarder:
    Type: String
    AllowedValues:
      - true
      - false
    Description: >-
      Determines whether the default configuration for the Datadog Lambda Log Forwarder is installed 
      as part of this stack. This is useful for sending logs to Datadog for use in Log Management or Cloud SIEM. 
      Customers who want to customize this setup to include specific custom tags, data scrubbing or redaction rules,
      or send logs using AWS PrivateLink should select “no” and install this independently
      (https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#installation).
    Default: true
Conditions:
  InstallForwarder:
    Fn::Equals:
      - !Ref InstallLambdaLogForwarder
      - true
  # A workaround for being unable to check list contains
  CloudSecurityPostureManagementPermissions:
    Fn::Or:
      - Fn::Equals:
        - Fn::Select:
          - 0
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${ProductIds},,,,,
              - { ProductIds: !Join [',', !Split [",", !Ref Products]] }
        - "Cloud Security Posture Management"
      - Fn::Equals:
        - Fn::Select:
          - 1
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${ProductIds},,,,,
              - { ProductIds: !Join [',', !Split [",", !Ref Products]] }
        - "Cloud Security Posture Management"
      - Fn::Equals:
        - Fn::Select:
          - 2
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${ProductIds},,,,,
              - { ProductIds: !Join [',', !Split [",", !Ref Products]] }
        - "Cloud Security Posture Management"
      - Fn::Equals:
        - Fn::Select:
          - 3
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${ProductIds},,,,,
              - { ProductIds: !Join [',', !Split [",", !Ref Products]] }
        - "Cloud Security Posture Management"
Resources:
  # A Macro used to generate policies for the integration IAM role based on user inputs
  DatadogAPICall:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_integration_api_call.yaml"
      Parameters:
        DatadogApiKey: !Ref APIKey
        DatadogAppKey: !Ref APPKey
        DatadogSite: !Ref DatadogSite
        RoleName: !Ref IAMRoleName
        Products: !Ref Products
  # The IAM role for Datadog integration
  DatadogIntegrationRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_integration_role.yaml"
      Parameters:
        ExternalId: !GetAtt DatadogAPICall.Outputs.ExternalId
        IAMRoleName: !Ref IAMRoleName
        CloudSecurityPostureManagementPermissions: !If [CloudSecurityPostureManagementPermissions, true, false]
        DdAWSAccountId: 464622532012
  # The Lambda function to ship logs from S3 and CloudWatch, custom metrics and traces from Lambda functions to Datadog
  # https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring
  ForwarderStack:
    Type: AWS::CloudFormation::Stack
    Condition: InstallForwarder
    Properties:
      TemplateURL: "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml"
      Parameters:
        DdApiKey: !Ref APIKey
        DdSite: !Ref DatadogSite
Outputs:
  IAMRoleName:
    Description: AWS IAM Role named to be used with the DataDog AWS Integration 
    Value: !Ref IAMRoleName
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Condition: InstallForwarder
    Value:
      Fn::GetAtt:
        - ForwarderStack
        - Outputs.DatadogForwarderArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Parameters:
        - Products
        - APIKey
        - APPKey
        - DatadogSite
        - IAMRoleName
        - InstallLambdaLogForwarder
    ParameterLabels:
      APIKey:
        default: "DatadogApiKey *"
      APPKey:
        default: "DatadogAppKey *"
      DatadogSite:
        default: "DatadogSite *"
