AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Streams
Parameters:
  ApiKey:
    Description: >-
      Your Datadog API Key
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ApiKey is required
  ServiceRoleArn:
    Description: >-
      The arn for the service role used by kinesis firehose
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ServiceRoleArn is required
  StreamRoleArn:
    Description: >-
      The arn for the stream used by the cloudwatch stream
    Type: String
    AllowedPattern: .+
    ConstraintDescription: StreamRoleArn is required
  IncludeNamespace:
    Description: >-
      A single namespace to turn all streams on for initially for testing purposes
    Type: String
    Default: ''
  DdSite:
    Description: >-
      Define your Datadog Site to send data to. For the Datadog EU site, set to datadoghq.eu
    Type: String
    AllowedPattern: .+
    Default: datadoghq.com
    ConstraintDescription: DdSite is required
Resources:
  DatadogStreamLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "datadog-metric-stream"
      RetentionInDays: 14
  HTTPLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref DatadogStreamLogs
      LogStreamName: "http_endpoint_delivery"
  S3Backup:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref DatadogStreamLogs
      LogStreamName: "s3_backup"
  DatadogStreamBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "datadog-aws-metric-stream-backup-${AWS::AccountId}-${AWS::Region}"
  DatadogMetricKinesisFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: "datadog-metrics-stream"
      DeliveryStreamType: "DirectPut"
      HttpEndpointDestinationConfiguration:
        BufferingHints:
          SizeInMBs: 3
          IntervalInSeconds: 60
        EndpointConfiguration:
          Url: "https://awsmetrics-http-intake.datad0g.com/v1/input"
          Name: "Event intake"
          AccessKey: !Ref ApiKey
        CloudWatchLoggingOptions:
          Enabled: True
          LogGroupName: !Ref DatadogStreamLogs
          LogStreamName: "http_endpoint_delivery"
        RoleARN: !Ref ServiceRoleArn
        S3BackupMode: "FailedDataOnly"
        S3Configuration:
          RoleARN: !Ref ServiceRoleArn
          BucketARN: !GetAtt DatadogStreamBackupBucket.Arn
          ErrorOutputPrefix: "datadog_stream"
          BufferingHints:
            SizeInMBs: 3
            IntervalInSeconds: 60
          CompressionFormat: "GZIP"
          CloudWatchLoggingOptions:
            Enabled: True
            LogGroupName: !Ref DatadogStreamLogs
            LogStreamName: "s3_backup"
      Tags:
        - Key: "Team"
          Value: "aws-integration"
        - Key: "StreamAccountID"
          Value: !Ref "AWS::AccountId"
  DatadogMetricStreamAllNamespaces:
    Type: AWS::CloudWatch::MetricStream
    Properties:
      Name: "datadog-metrics-stream"
      FirehoseArn: !GetAtt DatadogMetricKinesisFirehose.Arn
      RoleArn: !Ref StreamRoleArn
