AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Datadog AWS Integration
Parameters:
  ExternalId:
    Description: >-
      External ID for the Datadog role (generate at
      https://app.datadoghq.com/account/settings#integrations/amazon-web-services)
    Type: String
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  BasePermissions:
    Description: >-
      Customize the base permissions for the Datadog IAM role.
      Select "Core" to only grant Datadog permissions to a very limited set of metrics and metadata (not recommended).
    Type: String
    Default: Full
    AllowedValues:
      - Full
      - Core
  LogArchives:
    Description: >-
      S3 paths to store log archives for log rehydration. Separate multiple paths with comma,
      e.g., "my-bucket,my-bucket-with-path/path".
    Type: String
    Default: ''
  CloudTrails:
    Description: >-
      S3 buckets for the Datadog CloudTrail integration. Separate multiple buckets with commas,
      e.g., "bucket1,bucket2". Permissions will be automatically added to the Datadog integration IAM role.
      https://docs.datadoghq.com/integrations/amazon_cloudtrail/
    Type: String
    Default: ''
  CloudSecurityPostureManagementPermissions:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: >-
      Set this value to "true" to add permissions for Datadog's Cloud Security Posture Management product
      to monitor your AWS cloud resource configurations.
      You need this set to "true" to use Cloud Security Posture Management. You will also need "BasePermissions" set to "Full".
  DdAWSAccountId:
    Description: >-
      Datadog AWS account ID allowed to assume the integration IAM role. DO NOT CHANGE!
    Type: String
    Default: '464622532012'
Conditions:
  GrantFullPermissions:
    Fn::Equals:
      - Ref: BasePermissions
      - Full
  ShouldInstallCSPMPolicy:
    Fn::Equals:
      - Ref: CloudSecurityPostureManagementPermissions
      - true
Resources:
  DatadogIntegrationRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn-lint:
        config:
          # cfn-lint does not yet support "Fn::Transform"
          ignore_checks:
            - E3002
            - E3003
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${DdAWSAccountId}:root'
                - { DdAWSAccountId: !Ref DdAWSAccountId }
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Path: /
      RoleName: !Ref IAMRoleName
      ManagedPolicyArns:
        !If [
          ShouldInstallCSPMPolicy,
          ['arn:aws:iam::aws:policy/SecurityAudit'],
          !Ref AWS::NoValue,
        ]
      Policies:
        - PolicyName: DatadogAWSIntegrationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - !If
                - GrantFullPermissions
                - Effect: Allow
                  Resource: '*'
                  Action:
                    - 'amplify:ListApps'
                    - 'amplify:ListArtifacts'
                    - 'amplify:ListBackendEnvironments'
                    - 'amplify:ListBranches'
                    - 'amplify:ListDomainAssociations'
                    - 'amplify:ListJobs'
                    - 'amplify:ListWebhooks'
                    - 'apigateway:GET'
                    - 'aoss:BatchGetCollection'
                    - 'aoss:ListCollections'
                    - 'appstream:DescribeAppBlockBuilders'
                    - 'appstream:DescribeAppBlocks'
                    - 'appstream:DescribeApplications'
                    - 'appstream:DescribeFleets'
                    - 'appstream:DescribeImageBuilders'
                    - 'appstream:DescribeImages'
                    - 'appstream:DescribeStacks'
                    - 'autoscaling:Describe*'
                    - 'backup:List*'
                    - 'batch:DescribeJobQueues'
                    - 'batch:DescribeSchedulingPolicies'
                    - 'batch:ListSchedulingPolicies'
                    - 'bcm-data-exports:GetExport'
                    - 'bcm-data-exports:ListExports'
                    - 'bedrock:GetAgent'
                    - 'bedrock:GetAgentAlias'
                    - 'bedrock:GetFlow'
                    - 'bedrock:GetFlowAlias'
                    - 'bedrock:GetGuardrail'
                    - 'bedrock:GetImportedModel'
                    - 'bedrock:GetInferenceProfile'
                    - 'bedrock:GetMarketplaceModelEndpoint'
                    - 'bedrock:ListAgentAliases'
                    - 'bedrock:ListAgents'
                    - 'bedrock:ListFlowAliases'
                    - 'bedrock:ListFlows'
                    - 'bedrock:ListGuardrails'
                    - 'bedrock:ListImportedModels'
                    - 'bedrock:ListInferenceProfiles'
                    - 'bedrock:ListMarketplaceModelEndpoints'
                    - 'bedrock:ListPromptRouters'
                    - 'bedrock:ListProvisionedModelThroughputs'
                    - 'budgets:ViewBudget'
                    - 'cassandra:Select'
                    - 'cloudfront:GetDistributionConfig'
                    - 'cloudfront:ListDistributions'
                    - 'cloudtrail:DescribeTrails'
                    - 'cloudtrail:GetTrailStatus'
                    - 'cloudtrail:LookupEvents'
                    - 'cloudwatch:Describe*'
                    - 'cloudwatch:Get*'
                    - 'cloudwatch:List*'
                    - 'codeartifact:DescribeDomain'
                    - 'codeartifact:DescribePackageGroup'
                    - 'codeartifact:DescribeRepository'
                    - 'codeartifact:ListDomains'
                    - 'codeartifact:ListPackageGroups'
                    - 'codeartifact:ListPackages'
                    - 'codedeploy:BatchGet*'
                    - 'codedeploy:List*'
                    - 'codepipeline:ListWebhooks'
                    - 'cur:DescribeReportDefinitions'
                    - 'deadline:GetBudget'
                    - 'deadline:GetLicenseEndpoint'
                    - 'deadline:GetQueue'
                    - 'deadline:ListBudgets'
                    - 'deadline:ListFarms'
                    - 'deadline:ListFleets'
                    - 'deadline:ListLicenseEndpoints'
                    - 'deadline:ListMonitors'
                    - 'deadline:ListQueues'
                    - 'deadline:ListWorkers'
                    - 'directconnect:Describe*'
                    - 'dynamodb:Describe*'
                    - 'dynamodb:List*'
                    - 'ec2:Describe*'
                    - 'ec2:GetAllowedImagesSettings'
                    - 'ec2:GetEbsDefaultKmsKeyId'
                    - 'ec2:GetInstanceMetadataDefaults'
                    - 'ec2:GetSerialConsoleAccessStatus'
                    - 'ec2:GetSnapshotBlockPublicAccessState'
                    - 'ec2:GetTransitGatewayPrefixListReferences'
                    - 'ec2:SearchTransitGatewayRoutes'
                    - 'ecs:Describe*'
                    - 'ecs:List*'
                    - 'elasticache:Describe*'
                    - 'elasticache:List*'
                    - 'elasticfilesystem:DescribeAccessPoints'
                    - 'elasticfilesystem:DescribeFileSystems'
                    - 'elasticfilesystem:DescribeTags'
                    - 'elasticloadbalancing:Describe*'
                    - 'elasticmapreduce:Describe*'
                    - 'elasticmapreduce:List*'
                    - 'emr-containers:ListManagedEndpoints'
                    - 'emr-containers:ListSecurityConfigurations'
                    - 'emr-containers:ListVirtualClusters'
                    - 'es:DescribeElasticsearchDomains'
                    - 'es:ListDomainNames'
                    - 'es:ListTags'
                    - 'events:CreateEventBus'
                    - 'fsx:DescribeFileSystems'
                    - 'fsx:ListTagsForResource'
                    - 'glacier:GetVaultNotifications'
                    - 'glue:ListRegistries'
                    - 'grafana:DescribeWorkspace'
                    - 'greengrass:GetComponent'
                    - 'greengrass:GetConnectivityInfo'
                    - 'greengrass:GetCoreDevice'
                    - 'greengrass:GetDeployment'
                    - 'health:DescribeAffectedEntities'
                    - 'health:DescribeEventDetails'
                    - 'health:DescribeEvents'
                    - 'identitystore:DescribeGroup'
                    - 'identitystore:DescribeGroupMembership'
                    - 'identitystore:DescribeUser'
                    - 'identitystore:ListGroupMemberships'
                    - 'identitystore:ListGroups'
                    - 'identitystore:ListUsers'
                    - 'imagebuilder:GetContainerRecipe'
                    - 'imagebuilder:GetDistributionConfiguration'
                    - 'imagebuilder:GetImageRecipe'
                    - 'imagebuilder:GetInfrastructureConfiguration'
                    - 'imagebuilder:GetLifecyclePolicy'
                    - 'imagebuilder:GetWorkflow'
                    - 'imagebuilder:ListComponents'
                    - 'imagebuilder:ListContainerRecipes'
                    - 'imagebuilder:ListDistributionConfigurations'
                    - 'imagebuilder:ListImagePipelines'
                    - 'imagebuilder:ListImageRecipes'
                    - 'imagebuilder:ListImages'
                    - 'imagebuilder:ListInfrastructureConfigurations'
                    - 'imagebuilder:ListLifecyclePolicies'
                    - 'imagebuilder:ListWorkflows'
                    - 'kinesis:Describe*'
                    - 'kinesis:List*'
                    - 'lambda:GetPolicy'
                    - 'lambda:List*'
                    - 'lightsail:GetInstancePortStates'
                    - 'logs:DeleteSubscriptionFilter'
                    - 'logs:DescribeLogGroups'
                    - 'logs:DescribeLogStreams'
                    - 'logs:DescribeSubscriptionFilters'
                    - 'logs:FilterLogEvents'
                    - 'logs:PutSubscriptionFilter'
                    - 'logs:TestMetricFilter'
                    - 'macie2:GetAllowList'
                    - 'macie2:GetCustomDataIdentifier'
                    - 'macie2:ListAllowLists'
                    - 'macie2:ListCustomDataIdentifiers'
                    - 'macie2:ListMembers'
                    - 'macie2:GetMacieSession'
                    - 'managedblockchain:GetAccessor'
                    - 'managedblockchain:GetMember'
                    - 'managedblockchain:GetNetwork'
                    - 'managedblockchain:GetNode'
                    - 'managedblockchain:GetProposal'
                    - 'managedblockchain:ListAccessors'
                    - 'managedblockchain:ListInvitations'
                    - 'managedblockchain:ListMembers'
                    - 'managedblockchain:ListNodes'
                    - 'managedblockchain:ListProposals'
                    - 'memorydb:DescribeAcls'
                    - 'memorydb:DescribeMultiRegionClusters'
                    - 'memorydb:DescribeParameterGroups'
                    - 'memorydb:DescribeReservedNodes'
                    - 'memorydb:DescribeSnapshots'
                    - 'memorydb:DescribeSubnetGroups'
                    - 'memorydb:DescribeUsers'
                    - 'mobiletargeting:GetApps'
                    - 'mobiletargeting:GetCampaigns'
                    - 'mobiletargeting:GetChannels'
                    - 'mobiletargeting:GetEventStream'
                    - 'mobiletargeting:GetRecommenderConfigurations'
                    - 'mobiletargeting:GetSegments'
                    - 'mobiletargeting:ListJourneys'
                    - 'mobiletargeting:ListTemplates'
                    - 'oam:ListAttachedLinks'
                    - 'oam:ListSinks'
                    - 'organizations:Describe*'
                    - 'organizations:List*'
                    - 'osis:GetPipeline'
                    - 'osis:GetPipelineBlueprint'
                    - 'osis:ListPipelineBlueprints'
                    - 'osis:ListPipelines'
                    - 'proton:GetComponent'
                    - 'proton:GetDeployment'
                    - 'proton:GetEnvironment'
                    - 'proton:GetEnvironmentAccountConnection'
                    - 'proton:GetEnvironmentTemplate'
                    - 'proton:GetEnvironmentTemplateVersion'
                    - 'proton:GetRepository'
                    - 'proton:GetService'
                    - 'proton:GetServiceInstance'
                    - 'proton:GetServiceTemplate'
                    - 'proton:GetServiceTemplateVersion'
                    - 'proton:ListComponents'
                    - 'proton:ListDeployments'
                    - 'proton:ListEnvironmentAccountConnections'
                    - 'proton:ListEnvironmentTemplateVersions'
                    - 'proton:ListEnvironmentTemplates'
                    - 'proton:ListEnvironments'
                    - 'proton:ListRepositories'
                    - 'proton:ListServiceInstances'
                    - 'proton:ListServiceTemplateVersions'
                    - 'proton:ListServiceTemplates'
                    - 'proton:ListServices'
                    - 'qldb:ListJournalKinesisStreamsForLedger'
                    - 'rds:Describe*'
                    - 'rds:List*'
                    - 'redshift:DescribeClusters'
                    - 'redshift:DescribeLoggingStatus'
                    - 'redshift-serverless:ListEndpointAccess'
                    - 'redshift-serverless:ListManagedWorkgroups'
                    - 'redshift-serverless:ListNamespaces'
                    - 'redshift-serverless:ListRecoveryPoints'
                    - 'redshift-serverless:ListSnapshots'
                    - 'route53:List*'
                    - 'savingsplans:DescribeSavingsPlanRates'
                    - 'savingsplans:DescribeSavingsPlans'
                    - 's3:GetBucketLocation'
                    - 's3:GetBucketLogging'
                    - 's3:GetBucketNotification'
                    - 's3:GetBucketTagging'
                    - 's3:ListAccessGrants'
                    - 's3:ListAllMyBuckets'
                    - 's3:PutBucketNotification'
                    # For S3 Directory Buckets, the s3 calls are with the s3express prefix
                    # https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3express.html
                    - 's3express:GetBucketPolicy'
                    - 's3express:GetEncryptionConfiguration'
                    - 's3express:ListAllMyDirectoryBuckets'
                    - 'ses:Get*'
                    - 'ses:ListAddonInstances'
                    - 'ses:ListAddonSubscriptions'
                    - 'ses:ListAddressLists'
                    - 'ses:ListArchives'
                    - 'ses:ListContactLists'
                    - 'ses:ListCustomVerificationEmailTemplates'
                    - 'ses:ListMultiRegionEndpoints'
                    - 'ses:ListIngressPoints'
                    - 'ses:ListRelays'
                    - 'ses:ListRuleSets'
                    - 'ses:ListTemplates'
                    - 'ses:ListTrafficPolicies'
                    - 'secretsmanager:GetResourcePolicy'
                    - 'sms-voice:DescribeConfigurationSets'
                    - 'sms-voice:DescribeOptOutLists'
                    - 'sms-voice:DescribePhoneNumbers'
                    - 'sms-voice:DescribePools'
                    - 'sms-voice:DescribeProtectConfigurations'
                    - 'sms-voice:DescribeRegistrationAttachments'
                    - 'sms-voice:DescribeRegistrations'
                    - 'sms-voice:DescribeSenderIds'
                    - 'sms-voice:DescribeVerifiedDestinationNumbers'
                    - 'sns:GetSubscriptionAttributes'
                    - 'sns:List*'
                    - 'sns:Publish'
                    - 'social-messaging:GetLinkedWhatsAppBusinessAccount'
                    - 'social-messaging:ListLinkedWhatsAppBusinessAccounts'
                    - 'sqs:ListQueues'
                    - 'states:DescribeStateMachine'
                    - 'states:ListStateMachines'
                    - 'support:DescribeTrustedAdvisor*'
                    - 'support:RefreshTrustedAdvisorCheck'
                    - 'tag:GetResources'
                    - 'tag:GetTagKeys'
                    - 'tag:GetTagValues'
                    - 'timestream:DescribeEndpoints'
                    - 'timestream:ListTables'
                    - 'waf-regional:GetRule'
                    - 'waf-regional:GetRuleGroup'
                    - 'waf-regional:ListRuleGroups'
                    - 'waf-regional:ListRules'
                    - 'waf:GetRule'
                    - 'waf:GetRuleGroup'
                    - 'waf:ListRuleGroups'
                    - 'waf:ListRules'
                    - 'wafv2:GetLoggingConfiguration'
                    - 'wafv2:GetIPSet'
                    - 'wafv2:GetLoggingConfiguration'
                    - 'wafv2:GetRegexPatternSet'
                    - 'wafv2:GetRuleGroup'
                    - 'wafv2:ListLoggingConfigurations'
                    - 'workmail:DescribeOrganization'
                    - 'workmail:ListOrganizations'
                    - 'xray:BatchGetTraces'
                    - 'xray:GetTraceSummaries'
                - Effect: Allow
                  Resource: '*'
                  Action:
                    - 'cloudwatch:Get*'
                    - 'cloudwatch:List*'
                    - 'ec2:Describe*'
                    - 'tag:GetResources'
                    - 'tag:GetTagKeys'
                    - 'tag:GetTagValues'
        - Fn::Transform:
            - Name: 'DatadogPolicy'
              Parameters:
                PolicyType: LogArchive
                LogArchives: !Ref LogArchives
        - Fn::Transform:
            - Name: 'DatadogPolicy'
              Parameters:
                PolicyType: CloudTrail
                CloudTrails: !Ref CloudTrails
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required
        Parameters:
          - ExternalId
          - IAMRoleName
          - BasePermissions
      - Label:
          default: Optional
        Parameters:
          - LogArchives
          - CloudTrails
          - CloudSecurityPostureManagementPermissions
