AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Datadog AWS Integration
Parameters:
  ExternalId:
    Description: >-
      External ID for the Datadog role (generate at
      https://app.datadoghq.com/account/settings#integrations/amazon-web-services)
    Type: String
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String  
    Default: DatadogIntegrationRole
  BasePermissions:
    Description: >-
      Customize the base permissions for the Datadog IAM role.
      Select "Core" to only grant Datadog permissions to a very limited set of metrics and metadata (not recommended).
    Type: String
    Default: Full
    AllowedValues:
      - Full
      - Core
  LogArchives:
    Description: >-
      S3 paths to store log archives for log rehydration. Separate multiple paths with comma,
      e.g., "my-bucket,my-bucket-with-path/path".
    Type: String
    Default: ''
  CloudTrails:
    Description: >-
      S3 buckets for the Datadog CloudTrail integration. Separate multiple buckets with commas,
      e.g., "bucket1,bucket2". Permissions will be automatically added to the Datadog integration IAM role.
      https://docs.datadoghq.com/integrations/amazon_cloudtrail/
    Type: String
    Default: ''
  ResourceCollectionPermissions:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: >-
      Set this value to "true" to add permissions for Datadog to monitor your AWS cloud resource configurations.
      You need this set to "true" to use Cloud Security Posture Management. You will also need "BasePermissions" set to "Full".
  DdAWSAccountId:
    Description: >-
      Datadog AWS account ID allowed to assume the integration IAM role. DO NOT CHANGE!
    Type: String
    Default: "464622532012"
Conditions:
  GrantFullPermissions:
    Fn::Equals:
      - Ref: BasePermissions
      - Full
  ShouldInstallResourcePolicy:
    Fn::Equals:
      - Ref: ResourceCollectionPermissions
      - true
Resources:
  DatadogAWSResourceCollectionPolicy:
    Type: "AWS::IAM::Policy"
    Condition: ShouldInstallResourcePolicy
    Properties:
      PolicyName: DatadogAWSResourceCollectionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - "acm:DescribeCertificate"
              - "acm:ListCertificates"
              - "cloudfront:GetDistribution"
              - "cloudfront:ListDistributions"
              - "cloudtrail:DescribeTrails"
              - "cloudtrail:GetEventSelectors"
              - "cloudtrail:GetTrailStatus"
              - "config:DescribeConfigurationRecorderStatus"
              - "config:DescribeConfigurationRecorders"
              - "iam:GenerateCredentialReport"
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetAccountSummary"
              - "iam:GetCredentialReport"
              - "iam:GetLoginProfile"
              - "iam:GetPolicy"
              - "iam:GetPolicyVersion"
              - "iam:ListAttachedUserPolicies"
              - "iam:ListAttachedRolePolicies"
              - "iam:ListEntitiesForPolicy"
              - "iam:ListMFADevices"
              - "iam:ListPolicies"
              - "iam:ListRolePolicies"
              - "iam:ListRoles"
              - "iam:ListServerCertificates"
              - "iam:ListUserPolicies"
              - "iam:ListUsers"
              - "iam:ListVirtualMFADevices"
              - "iam:GetRolePolicy"
              - "kms:GetKeyPolicy"
              - "kms:GetKeyRotationStatus"
              - "kms:ListAliases"
              - "kms:ListKeys"
              - "lambda:GetPolicy"
              - "lambda:ListFunctions"
              - "redshift:DescribeClusterParameterGroups"
              - "redshift:DescribeClusterParameters"
              - "redshift:DescribeLoggingStatus"
              - "rds:DescribeDBSecurityGroups"
              - "rds:DescribeDBSnapshotAttributes"
              - "rds:DescribeDBSnapshots"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLogging"
              - "s3:GetBucketPolicy"
              - "s3:GetBucketPolicyStatus"
              - "s3:GetBucketPublicAccessBlock"
              - "s3:GetBucketVersioning"
              - "s3:GetEncryptionConfiguration"
              - "sns:GetSubscriptionAttributes"
              - "sns:GetTopicAttributes"
              - "sns:ListSubscriptions"
              - "sns:ListTopics"
              - "sqs:GetQueueAttributes"
              - "sqs:ListQueues"
      Roles:
        - !Ref DatadogIntegrationRole
  DatadogIntegrationRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn-lint:
        config:
          # cfn-lint does not yet support "Fn::Transform"
          ignore_checks:
          - E3002
          - E3003
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${DdAWSAccountId}:root'
                - { DdAWSAccountId: !Ref DdAWSAccountId}
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Path: /
      RoleName: !Ref IAMRoleName
      Policies:
        - PolicyName: DatadogAWSIntegrationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - !If
              - GrantFullPermissions
              -
                Effect: Allow
                Resource: '*'
                Action:
                  - 'apigateway:GET'
                  - 'autoscaling:Describe*'
                  - 'budgets:ViewBudget'
                  - 'cloudfront:GetDistributionConfig'
                  - 'cloudfront:ListDistributions'
                  - 'cloudtrail:DescribeTrails'
                  - 'cloudtrail:GetTrailStatus'
                  - 'cloudtrail:LookupEvents'
                  - 'cloudwatch:Describe*'
                  - 'cloudwatch:Get*'
                  - 'cloudwatch:List*'
                  - 'codedeploy:List*'
                  - 'codedeploy:BatchGet*'
                  - 'directconnect:Describe*'
                  - 'dynamodb:List*'
                  - 'dynamodb:Describe*'
                  - 'ec2:Describe*'
                  - 'ecs:Describe*'
                  - 'ecs:List*'
                  - 'elasticache:Describe*'
                  - 'elasticache:List*'
                  - 'elasticfilesystem:DescribeAccessPoints'
                  - 'elasticfilesystem:DescribeFileSystems'
                  - 'elasticfilesystem:DescribeTags'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticmapreduce:List*'
                  - 'elasticmapreduce:Describe*'
                  - 'es:ListTags'
                  - 'es:ListDomainNames'
                  - 'es:DescribeElasticsearchDomains'
                  - 'fsx:DescribeFileSystems'
                  - 'fsx:ListTagsForResource'
                  - 'health:DescribeEvents'
                  - 'health:DescribeEventDetails'
                  - 'health:DescribeAffectedEntities'
                  - 'kinesis:List*'
                  - 'kinesis:Describe*'
                  - 'lambda:GetPolicy'
                  - 'lambda:List*'
                  - 'logs:TestMetricFilter'
                  - 'logs:PutSubscriptionFilter'
                  - 'logs:DeleteSubscriptionFilter'
                  - 'logs:DescribeSubscriptionFilters'
                  - 'organizations:DescribeOrganization'
                  - 'rds:Describe*'
                  - 'rds:List*'
                  - 'redshift:DescribeClusters'
                  - 'redshift:DescribeLoggingStatus'
                  - 'route53:List*'
                  - 's3:GetBucketLogging'
                  - 's3:GetBucketLocation'
                  - 's3:GetBucketNotification'
                  - 's3:GetBucketTagging'
                  - 's3:ListAllMyBuckets'
                  - 's3:PutBucketNotification'
                  - 'ses:Get*'
                  - 'sns:List*'
                  - 'sns:Publish'
                  - 'sqs:ListQueues'
                  - 'states:ListStateMachines'
                  - 'states:DescribeStateMachine'
                  - 'support:*'
                  - 'tag:GetResources'
                  - 'tag:GetTagKeys'
                  - 'tag:GetTagValues'
                  - 'xray:BatchGetTraces'
                  - 'xray:GetTraceSummaries'
              -
                Effect: Allow
                Resource: '*'
                Action:
                  - 'cloudwatch:Get*'
                  - 'cloudwatch:List*'
                  - 'ec2:Describe*'
                  - 'support:*'
                  - 'tag:GetResources'
                  - 'tag:GetTagKeys'
                  - 'tag:GetTagValues'
        - Fn::Transform:
          - Name: 'DatadogPolicy'
            Parameters:
              PolicyType: LogArchive
              LogArchives: !Ref LogArchives
        - Fn::Transform:
          - Name: 'DatadogPolicy'
            Parameters:
              PolicyType: CloudTrail
              CloudTrails: !Ref CloudTrails
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - ExternalId
        - IAMRoleName
        - BasePermissions
    - Label:
        default: Optional
      Parameters:
        - LogArchives
        - CloudTrails
        - ResourceCollectionPermissions
