AWSTemplateFormatVersion: "2010-09-09"
Description: Datadog AWS Account Integration
Parameters:
  DdApiKey:
    Description: Datadog API Key
    Type: String
    NoEcho: true
  DdAppKey:
    Description: Datadog Application Key
    Type: String
    NoEcho: true
  DdSite:
    Description: Datadog Site
    Type: String
    Default: datadoghq.com
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - ddog-gov.com
  DdInstallLambdaLogForwarder:
    Description: Install Lambda Log Forwarder
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DdEnableCspm:
    Description: Enable Cloud Security Posture Management
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  DdDisableMetricCollection:
    Description: Disable Metric Collection
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  DdDisableResourceCollection:
    Description: Disable Resource Collection
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  DdIamIntegrationRoleName:
    Description: Datadog IAM Integration Role Name
    Type: String
    Default: DatadogIntegrationRole
Resources:
  DatadogAccountIntegrationLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        -  Fn::Sub: "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: DatadogAccountIntegrationLambdaFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - Fn::Sub: "arn:${AWS::Partition}:iam::*:role/OrganizationAccountAccessRole"
  DatadogAccountIntegrationTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "datadog-account-integration-trail-bucket"
  DatadogAccountIntegrationTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref "DatadogAccountIntegrationTrailBucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: 
              - Fn::Sub: "arn:${AWS::Partition}:s3:::datadog-account-integration-trail-bucket"
            Condition:
              StringLike:
                "aws:SourceArn": 
                  - Fn::Sub: "arn:${AWS::Partition}:cloudtrail:*:${AWS::AccountId}:trail/DatadogAccountIntegrationTrail"
          - Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: 
              - Fn::Sub: "arn:${AWS::Partition}:s3:::datadog-account-integration-trail-bucket/datadog-account-integration/*"
            Condition:
              StringLike:
                "aws:SourceArn": 
                  - Fn::Sub: "arn:${AWS::Partition}:cloudtrail:*:${AWS::AccountId}:trail/DatadogAccountIntegrationTrail"
  DatadogAccountIntegrationTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: "DatadogAccountIntegrationTrail"
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EventSelectors:
        - IncludeManagementEvents: true
          ReadWriteType: WriteOnly
      S3BucketName: !Ref "DatadogAccountIntegrationTrailBucket"
      S3KeyPrefix: "datadog-account-integration"
    DependsOn:
      - DatadogAccountIntegrationTrailBucketPolicy
        DatadogAccountIntegrationTrailBucket
  DatadogAccountIntegrationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.13
      Timeout: 600
      Code:
        ZipFile: |
          import os
          import time
          import boto3

          def handler(event, context):
              if event.get("source") != "aws.organizations":
                  return

              if event.get("detail").get("eventName") != "CreateAccountResult":
                  return

              if event.get("detail").get("serviceEventDetails").get("createAccountStatus").get("state") != "SUCCEEDED":
                  return

              # We need to add a sleep here, to allow AWS finish provisioning of a new AWS account.
              time.sleep(180)

              newAccountId = event.get("detail").get("serviceEventDetails").get("createAccountStatus").get("accountId")
              role = f"arn:aws:iam::{newAccountId}:role/OrganizationAccountAccessRole"
              session = boto3.Session()

              sts = session.client("sts")
              response = sts.assume_role(RoleArn=role, RoleSessionName="datadog-aws-provisioning")

              new_session = boto3.Session(
                  aws_access_key_id=response["Credentials"]["AccessKeyId"],
                  aws_secret_access_key=response["Credentials"]["SecretAccessKey"],
                  aws_session_token=response["Credentials"]["SessionToken"],
              )

              client = new_session.client("cloudformation")

              response = client.create_stack(
                  StackName="Datadog-Integration-New-AWS-Account-cf-stack",
                  TemplateURL="https://datadog-cloudformation-template-quickstart.s3.amazonaws.com/aws/v2.0.5/main_v2.yaml",
                  Parameters=[
                      {
                          "ParameterKey": "APIKey",
                          "ParameterValue": os.environ["DD_API_KEY"],
                      },
                      {
                          "ParameterKey": "APPKey",
                          "ParameterValue": os.environ["DD_APP_KEY"],
                      },
                      {
                          "ParameterKey": "DatadogSite",
                          "ParameterValue": os.environ["DD_SITE"],
                      },
                      {
                          "ParameterKey": "InstallLambdaLogForwarder",
                          "ParameterValue": os.environ["DD_INSTALL_LAMBDA_LOG_FORWARDER"],
                      },
                      {
                          "ParameterKey": "DisableMetricCollection",
                          "ParameterValue": os.environ["DD_DISABLE_METRIC_COLLECTION"],
                      },
                      {
                          "ParameterKey": "DisableResourceCollection",
                          "ParameterValue": os.environ["DD_DISABLE_RESOURCE_COLLECTION"],
                      },
                      {
                          "ParameterKey": "CloudSecurityPostureManagement",
                          "ParameterValue": os.environ["DD_ENABLE_CSPM"],
                      },
                      {
                          "ParameterKey": "IAMRoleName",
                          "ParameterValue": os.environ["DD_IAM_INTEGRATION_ROLE_NAME"],
                      },
                  ],
                  Capabilities=["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"],
                  EnableTerminationProtection=False,
                  TimeoutInMinutes=10,
              )

              stack_id = response["StackId"]

              while True:
                  response = client.describe_stacks(StackName=stack_id)
                  if response["Stacks"][0]["StackStatus"] == "CREATE_IN_PROGRESS":
                      time.sleep(10)
                      continue

                  if response["Stacks"][0]["StackStatus"] == "CREATE_COMPLETE":
                      print(f"Datadog Integration for account {newAccountId} has been successfully created")
                      break

                  print(f"Datadog Integration for account {newAccountId} failed to create")
                  print(response)
                  RuntimeError(f"Datadog Integration for account {newAccountId} failed to create")
      Environment:
        Variables:
          DD_API_KEY: !Ref DdApiKey
          DD_APP_KEY: !Ref DdAppKey
          DD_SITE: !Ref DdSite
          DD_INSTALL_LAMBDA_LOG_FORWARDER: !Ref DdInstallLambdaLogForwarder
          DD_ENABLE_CSPM: !Ref DdEnableCspm
          DD_DISABLE_METRIC_COLLECTION: !Ref DdDisableMetricCollection
          DD_DISABLE_RESOURCE_COLLECTION: !Ref DdDisableResourceCollection
          DD_IAM_INTEGRATION_ROLE_NAME: !Ref DdIamIntegrationRoleName
      Role:
        Fn::GetAtt:
          - "DatadogAccountIntegrationLambdaFunctionRole"
          - "Arn"
  DatadogAccountIntegrationEventLambdaPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Fn::GetAtt: 
          - "DatadogAccountIntegrationLambdaFunction"
          - "Arn"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "DatadogAccountIntegrationEventRule"
          - "Arn"
  DatadogAccountIntegrationEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: 'DatadogAccountIntegrationEventBridgeRule'
      Description: 'Datadog Account Integration EventBridge Rule'
      EventPattern:
        source:
          - aws.organizations
        detail:
          eventName:
            - CreateAccountResult
          serviceEventDetails:
            createAccountStatus:
              - SUCCEEDED
      State: ENABLED
      Targets:
        - 
          Arn: 
            Fn::GetAtt: 
              - "DatadogAccountIntegrationLambdaFunction"
              - "Arn"
          Id: 'DatadogAccountIntegration'
