# version: <VERSION_PLACEHOLDER>
AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration Attach Permissions
Parameters:
  DatadogIntegrationRole:
    Type: String
    Description: The name of the IAM role that has been integrated with Datadog.
  AccountId:
    Type: String
    Description: The AWS account ID of the account integrated in Datadog.
Rules:
  ValidateAccountId:
    Assertions:
      - Assert: !Equals [!Ref AccountId, !Ref "AWS::AccountId"]
        AssertDescription: "The AWS Account Id of the the account integrated in Datadog does not match the AWS Account Id of the account where this stack will be created."
Resources:
  DatadogAttachIntegrationPermissions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws_attach_integration_permissions/<VERSION_PLACEHOLDER>/attach_integration_permissions.yaml"
      Parameters:
        DatadogIntegrationRole: !Ref DatadogIntegrationRole
        AccountId: !Ref AccountId
  DatadogAttachSecurityAuditPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws_attach_integration_permissions/<VERSION_PLACEHOLDER>/attach_security_audit_policy.yaml"
      Parameters:
        DatadogIntegrationRole: !Ref DatadogIntegrationRole
  
