general:
  auth:
    default: "<REPLACE_AWS_PROFILE>"
  s3_bucket: datadog-cloudformation-templates-aws-taskcat-test

project:
  name: aws-streams
  regions:
  - ap-northeast-3
tests:
  default:
    template: ./streams_main.yaml
    parameters:
      ApiKey: "<REPLACE_DD_API_KEY>"
      DdSite: "datad0g.com"
      Regions: "ap-northeast-3"
