name: cfn-lint
on:
  - push
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@be676baed6db1a0d44f2f3ea59554623dc5b4109 # v2.4.9
      with:
        args: "**/*.yaml"
